build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/DependenciesVersions.kt, goms-domain/src/main/kotlin/com/goms/v2/domain/account/Authority.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/AccountRepository.kt, goms-infrastructure/build.gradle.kts, goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/PropertiesScanConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/exception/ErrorCode.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/ExceptionHandlerFilter.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/JwtRequestFilter.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/RequestLogFilter.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/config/FilterConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/SecurityConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/handler/CustomAccessDeniedHandler.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/handler/CustomAuthenticationEntryPoint.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/JwtParser.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/exception/ExpiredRefreshTokenException.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/exception/InvalidTokenException.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/exception/InvalidTokenTypeException.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/properties/JwtExpTimeProperties.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/properties/JwtProperties.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/principal/StudentCouncilDetails.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/principal/StudentCouncilDetailsService.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/principal/StudentDetails.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/principal/StudentDetailsService.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/mapper/AccountMapper.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt, goms-infrastructure/src/main/resources/application-local.yml
=> 🔀 :: SpringSecurity 관련 설정 

.github/CI.yml, .github/workflows/CI.yml
=> 🔀 :: CI 작성

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/CreateOutingUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/common/property/studentCouncil/OutingUUIDExpTimeProperties.kt, goms-domain/src/main/kotlin/com/goms/v2/domain/studentCouncil/OutingUUID.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/studentCouncil/OutingUUIDRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/PropertiesScanConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/studentCouncil/entity/OutingUUIDJpaEntity.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/studentCouncil/entity/OutingUUIDRedisEntity.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/studentCouncil/mapper/OutingUUIDMapper.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/studentCouncil/repository/OutingUUIDJpaRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/studentCouncil/repository/OutingUUIDRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/CreateOutingUseCaseTest.kt
+ QR 생성 기능을 추가하였습니다.
+ QR 생성 UseCase를 추가하였습니다.
+ QR 생성 api를 추가하였습니다.
+ QR 생성 테스트 코드를 추가하였습니다.
+ 코드 컨벤션이 지켜지지 않은 곳이 있다면 알려주세요!
=> 🔀 :: QR 생성 기능 추가

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/SaveOutingBlackListUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/domain/outing/OutingBlackList.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingBlackListRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/entity/OutingBlackListRedisEntity.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/mapper/OutingBlackListMapper.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingBlackListJpaRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingBlackListRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/SaveOutingBlackListUseCaseTest.kt
+ 블랙리스트 전환 기능을 구현했습니다.
+ 블랙리스트 전환 UseCase를 추가하였습니다.
+ 블랙리스트 전환 api를 추가하였습니다.
+ 블랙리스트 전환 테스트 코드를 추가하였습니다.
+ 잘못된 부분이나 코드 컨벤션이 지켜지지 않은 곳이 있다면 알려주세요!
=> 블랙리스트 전환 기능 추가

goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/AuthCodeNotFoundException.kt, goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/AuthCodeNotMatchException.kt, goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/AuthenticationNotFoundException.kt, goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/TooManyAuthCodeRequestException.kt, goms-application/src/main/kotlin/com/goms/v2/domain/email/usecase/SendEmailUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/email/usecase/VerifyAuthCodeUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/gloabl/exception/ErrorCode.kt, goms-domain/src/main/kotlin/com/goms/v2/domain/email/Authentication.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/email/entity/AuthenticationRedisEntity.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/email/EmailAuthController.kt
- 인증번호 검증을 위한 기능을 구현하였습니다.
- 이메일로 받은 인증번호를 검증하는 UseCase를 작성하였습니다.
- 이메일로 받은 인증번호를 검증하는 api를 작성하였습니다.
- 잘못된 코드 컨벤션이 있는지 확인해주세요!
=> 🔀 :: 인증번호 검증 기능 구현

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/DeleteOutingBlacklistUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingBlackListRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingBlackListRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/DeleteOutingBlackListUseCaseTest.kt
+ 블랙리스트 삭제 기능을 구현했습니다.
+ 블랙리스트 삭제 UseCase를 추가했습니다.
+ 블랙리스트 삭제 api를 추가했습니다.
+ 블랙리스트 삭제 테스트 코드를 추가했습니다.
코드 컨벤션이 지켜지지 않은 곳이 있다면 알려주세요!!
=> 🔀 :: 블랙리스트 삭제 기능 구현

goms-application/src/main/kotlin/com/goms/v2/common/util/AccountUtil.kt, goms-application/src/main/kotlin/com/goms/v2/domain/account/data/dto/ProfileDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/account/data/dto/StudentNumberDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/QueryAccountProfileUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/late/LateRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/entity/LateJpaEntity.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/repository/LateJpaRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/repository/LateRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/dto/response/ProfileHttpResponse.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/dto/response/StudentNumHttpResponse.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/mapper/AccountDataMapper.kt, goms-presentation/src/test/kotlin/com/goms/v2/common/AnyValueObjectGenerator.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/account/QueryAccountProfileUseCaseTest.kt
- 프로필 반환 기능을 추가하였습니다.
- 회원이 자신의 프로필을 볼 수 있는 UseCase를 작성하였습니다.
- 회원이 자신의 프로필을 볼 수 있는 api를 작성하였습니다.
- 회원이 자신의 프로필을 볼 수 있는 로직에 대한 테스트코드를 작성하였습니다.
- 필요없는 import를 삭제하였습니다.
- 잘못된 컨벤션이 있는지 확인해주세요.
=> 🔀 :: 프로필 반환 기능

buildSrc/src/main/kotlin/AllOpen.kt, goms-application/build.gradle.kts, goms-application/src/main/kotlin/com/goms/v2/common/annotation/UseCaseWithReadOnlyTransaction.kt, goms-application/src/main/kotlin/com/goms/v2/domain/outing/data/dto/OutingAccountDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/QueryOutingAccountUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/ComponentScanConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/SecurityConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/mapper/OutingMapper.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingJpaRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/AuthController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/email/EmailAuthController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/OutingController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/dto/response/OutingAccountHttpResponse.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/mapper/OutingDataMapper.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/QueryOutingAccountUseCaseTest.kt
- 현재 외출중인 학생을 반환하는 기능을 추가하였습니다.
- 현재 외출중인 학생을 반환하는 UseCase를 추가하였습니다.
- 현재 외출중인 학생을 반환하는 api를 추가하였습니다.
- endpoint에 버전을 v1에서 v2로 변경하였습니다.
- `UseCaseWithReadOnlyTransaction` 이라는 어노테이션을 생성하였습니다.
- 컨벤션에 맞지 않는 내용이 있는지 확인해주세요.
=> 🔀 :: 현재 외출중인 학생 리스트 반환 기능 구현

goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/QueryOutingCountUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/OutingController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/dto/response/OutingCountHttpResponse.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/mapper/OutingDataMapper.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/QueryOutingCountUseCaseTest.kt
- 현재 외출중인 학생 카운트 기능을 추가하였습니다.
- 현재 외출중인 학생 카운트 UseCase를 추가하였습니다.
- 현재 외출중인 학생 카운트 api를 추가하였습니다.
- 컨벤션에 맞지 않는 코드가 있는지 확인해주세요.
=> 🔀 :: 현재 외출중인 학생 카운트 기능 구현

goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/SearchOutingAccountUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/SearchOutingUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingRepository.kt, goms-infrastructure/build.gradle.kts, goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/QueryDslConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingJpaRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/OutingController.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/SearchOutingAccountUseCaseTest.kt
- 현재 외출중인 학생을 검색하는 기능을 구현하였습니다.
- 현재 외출중인 학생을 검색하는 UseCase를 추가하였습니다.
- 현재 외출중인 학생을 검색하는 api를 추가하였습니다.
- 컨벤션에 맞지 않는 부분이 있는지 확인해주세요.
=> 🔀 :: 현재 외출중인 학생 검색 기능 구현

goms-application/src/main/kotlin/com/goms/v2/common/annotation/UseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/ValidateOutingTimeUseCase.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/ComponentScanConfig.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/OutingController.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/ValidateOutingTimeUseCaseTest.kt
- 외출 가능 시간 검증 기능을 구현하였습니다.
- 외출이 가능한 시간(수요일 6시50분 ~ 7시25분)인지 검증하는 UseCase를 추가하였습니다.
- 외출이 가능한 시간(수요일 6시50분 ~ 7시25분)인지 검증하는 api를 추가하였습니다.
- `UseCase`어노테이션을 생성하였습니다.
- 컨벤션에 맞지 않는 부분이 있는지 확인해주세요.
=> 🔀 :: 외출 가능 시간 검증 기능 구현

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/data/dto/AccountDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/data/dto/AllAccountDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/QueryAllAccountUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/account/AccountRepository.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingBlackListRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/mapper/OutingBlackListMapper.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingBlackListRepositoryImpl.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingJpaRepository.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/dto/response/AllAccountHttpResponse.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/mapper/StudentCouncilDataMapper.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/QueryAllAccountUseCaseTest.kt
+ 사용자 전체 리스트 기능을 구현하였습니다.
+ 사용자 전체 리스트 usecase를 추가하였습니다.
+ 사용자 전체 리스트 api를 추가하였습니다.
+ 사용자 전체 리스트 테스트 코드를 추가하였습니다.
+ 코드 컨벤션이 지켜지지 않은 곳이 있다면 알려주세요!!
=> 🔀 :: 사용자 전체 리스트 기능 구현

goms-application/src/main/kotlin/com/goms/v2/domain/late/data/dto/LateRankDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/late/usecase/QueryLateRankUseCase.kt, goms-application/src/test/kotlin/com/goms/v2/common/AnyValueObjectGenerator.kt, goms-application/src/test/kotlin/com/goms/v2/domain/late/QueryLateRankUseCaseTest.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/late/LateRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/repository/LateRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/late/LateController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/late/dto/LateRankHttpResponse.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/late/mapper/LateDataMapper.kt
- 지각생 랭킹 기능을 구현하였습니다.
- 지각생 랭킹 UseCase를 추가하였습니다.
- 지각생 랭킹 api를 추가하였습니다.
- 코드컨벤션에 맞지 않는 내용이 있는지 확인해주세요.
=> 🔀 :: 지각생 랭킹 기능 구현

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/data/dto/GrantAuthorityDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/GrantAuthorityUseCase.kt, goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/GrantAuthorityUseCaseTest.kt, goms-domain/src/main/kotlin/com/goms/v2/domain/account/Account.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/dto/request/GrantAuthorityHttpRequest.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/mapper/StudentCouncilDataMapper.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
+ 권한 수정 기능을 구현하였습니다.
+ 권한 수정 UseCase를 추가하였습니다.
+ 권한 수정 api를 추가하였습니다.
+ 권한 수정 UseCase 테스트 코드를 추가하였습니다.
+ 권한 수정 Controller 테스트 코드를 추가하였습니다.
+ 코드 컨벤션이 잘못된게 있다면 알려주세요!!
+ Controller 테스트 코드를 처음 써봐서 아직 미숙한 부분이 있습니다 잘못된게 있다면 알려주세요!!
=> 🔀 :: 권한 수정 기능 구현

goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/ReissueTokenUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/email/usecase/SendEmailUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/email/usecase/VerifyAuthCodeUseCase.kt, goms-application/src/test/kotlin/com/goms/v2/common/AnyValueObjectGenerator.kt, goms-application/src/test/kotlin/com/goms/v2/domain/email/SendEmailUseCaseTest.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/email/EmailAuthController.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/email/EmailAuthControllerTest.kt
- 이메일 인증을 성공했을때 토큰을 발급하는 기능을 추가하였습니다.
- 이메일 전송 UseCase에 대한 테스트코드를 추가하였습니다.
- 이메일 전송 Controller에 대한 테스트코드를 추가하였습니다.
- 이메일 인증시 성공하면 토큰을 반환해주는 기능을 추가하였습니다.
- 컨벤션에 맞지 않는 내용이 있는지 확인해주세요.
- 처음에 이메일 인증 서비스에 대해 이해를 잘 못해 구현하는걸 빼먹었는데 잘 구현했는지 확인해주세요.
=> 🔀 :: 이메일 인증 관련 기능 구현 & 테스트코드 작성

goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt
- 외출 / 복귀 controller 테스트코드 작성
- 외출 / 복귀 controller에 대한 테스트코드를 작성하였습니다.
- 컨벤션에 맞지 않은 부분이 있는지 확인해주세요
=> 🔀:: 외출 / 복귀 controller 테스트 코드 작성

goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt
- controller 테스트코드를 작성하였습니다.
- 외출현황 리스트를 반환하는 controller의 테스트코드를 MockMvc를 이용해서 작성하였습니다.
- 컨벤션에 맞지 않는 부분이 있는지 확인해주세요.
=> 🔀 :: 외출 현황 리스트 테스트코드 작성

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/data/dto/SearchAccountDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/SearchAccountUseCase.kt, goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/SearchAccountUseCaseTest.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/account/AccountRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/mapper/StudentCouncilDataMapper.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
+ 사용자 검색 기능을 구현했습니다.
+ 사용자 검색 UseCase를 추가했습니다.
+ 사용자 검색 api를 추가했습니다.
+ 사용자 검색 UseCase 테스트 코드를 추가했습니다.
+ 사용자 검색 컨트롤러 테스트 코드를 추가했습니다.
+ 코드 컨벤션이 잘못된 곳이 있다면 알려주세요!!
+ 컨트롤러 테스트 코드에서 잘못된 부분이 있다면 알려주세요!!
=> 🔀 :: 사용자 검색 기능 구현

goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt
- 현재 외출중인 학생의 수를 카운트 하는 controller의 테스트코드를 작성하였습니다.
- 코드 컨벤션에 맞지 않은 부분이 있는지 확인해주세요.
=> 🔀 :: 외출중인 학생 카운트 controller 테스트코드 작성

goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
+ qr 생성 controller에 대한 테스트 코드를 작성했습니다.
+ 코드 컨벤션이 맞지 않는 곳이 있다면 알려주세요!
=> 🔀 :: QR 생성 controller 테스트 코드 

goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
+ 블랙리스트 전환 controller 테스트 코드를 작성했습니다.
+ 코드 컨벤션이 잘못된 곳이 있다면 알려주세요!
=> 🔀 :: 블랙리스트 전환 controller 테스트 코드

goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
+ 블랙리스트 취소 controller 테스트 코드를 작성했습니다.
+ 코드 컨벤션이 잘못된 곳이 있다면 알려주세요!
=> 🔀 :: 블랙리스트 취소 controller 테스트 코드 추가

goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt
- controller 테스트코드를 작성하였습니다.
- 현재 외출중인 학생을 검색하는 controller에 대한 테스트코드를 작성하였습니다.
- 컨벤션에 맞지 않은 부분이 있으면 피드백 부탁드립니다.
=> 🔀 :: 외출중인 학생 검색 controller 테스트 코드

goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
+ 사용자 전체 리스트 controller 테스트 코드를 작성했습니다.
+ 코드 컨벤션이 잘못된 곳이 있다면 알려주세요!
=> 🔀 :: 사용자 전체 리스트 controller 테스트 코드 추가

goms-presentation/src/test/kotlin/com/goms/v2/domain/email/EmailAuthControllerTest.kt
- controller 테스트코드를 작성하였습니다.
- 이메일 인증으로 로그인하는 controller의 테스트코드를 작성하였습니다.
=> 🔀 :: 이메일 인증번호 인증 controller 테스트 코드

goms-presentation/src/test/kotlin/com/goms/v2/domain/late/LateControllerTest.kt
+ 지각 랭킹 확인 controller 테스트 코드를 작성했습니다.
+ 코드 컨벤션이 잘못된 곳이 있다면 알려주세요!
=> 🔀 :: 지각 랭킹 확인 controller 테스트 코드 추가

goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt
- 현재 외출가능한 시간인지 검증하는 controller 테스트코드를 작성하였습니다.
- 컨벤션에 맞지 않은 내용이 있는지 확인해주세요.
=> 🔀 :: 외출 가능 시간인지 검증 controller 테스트 코드

goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt
- controller 테스트코드를 작성하였습니다.
- 프로필을 확인하는 controller의 테스트코드를 작성하였습니다.
=> 🔀 :: 프로필 반환 controller 테스트코드

goms-application/src/main/kotlin/com/goms/v2/domain/account/data/dto/ProfileDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/QueryAccountProfileUseCase.kt, goms-application/src/test/kotlin/com/goms/v2/domain/account/QueryAccountProfileUseCaseTest.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/dto/response/ProfileHttpResponse.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt
- profileDto의 컬럼을 수정하였습니다.
- profileDto에서 accountIdx 컬럼을 삭제하였습니다.
- 제가 accountIdx를 삭제하지 않은 부분이 있는지 확인해주세요.
=> 🔀 :: profileDto에서 accountIdx 삭제하기

goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/SearchOutingAccountUseCase.kt
- 반환할때 return를 삭제하였습니다.
- 반환할때 return 말고 = 을 사용해서 반환하였습니다.
=> 🔀 :: return문 말고 = 을 사용해서 반환하기

goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/dto/OAuthTokenDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/dto/OAuthUserInfoDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/auth/spi/OAuthPort.kt, goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/SignInUseCase.kt, goms-application/src/test/kotlin/com/goms/v2/domain/auth/SignInUseCaseTest.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/GAuthAdapter.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/mapper/GAuthDataMapper.kt
- GAuthPort를 좀 더 추상화 시키겠습니다. 
- GAuthPort를 OAuthPort로  변경하였습니다.
=> 🔀 :: OAuthPort로 클래스명 변경

goms-infrastructure/src/main/kotlin/com/goms/v2/GomsV2Application.kt
- 토큰 만료시간에 대한 timeZone을 설정해놓지 않았습니다.
- timeZone을 서울로 설정하였습니다.
=> 🔀 :: timeZone 설정하기

.github/workflows/CD-Dev.yml
- CD의 결과물을 알려주는 Job이 없어 CD가 성공했는지 실패했는지 보기 번거로워서 추가 했습니다.
- 작업별 띄어쓰기를 추가하였습니다.
- 결과에 따라 디스코드 알림을 보내도록 구현하였습니다.
- FCM_FILE_URL 환경변수를 추가하였습니다.
=> 🔀 :: CD-Dev 결과 디스코드 알림 Job 추가

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/SearchAccountUseCase.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/mapper/AccountDataMapper.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/mapper/StudentCouncilDataMapper.kt
+ boolean type 변수를 mapping 하면 false로만 mapping이 되는걸 발견 했습니다.
+ boolean type 변수를 직접 mapping 해주었습니다.
+ 변수명 오타가 있어 수정하였습니다.
+ 잘못된 내용이 있다면 알려주세요!
=> boolean 타입 변수 Mapping 오류 수정

goms-infrastructure/src/main/resources/application-prod.yml, goms-infrastructure/src/main/resources/application.yml
- yml에서 profiles.active관련 setting을 하였습니다.
- profiles.active의 값을 prod로 설정하였습니다.
=> 🔀 :: profiles.active setting

goms-presentation/src/main/kotlin/com/goms/v2/domain/HealthCheckController.kt
+ HealthCheck Message 변경
+ HealthCheck시 반환되는 Message에서 버전을 추가하였습니다.
=> 🔀 :: healthCheck message 변경

.github/workflows/CD.yml
+ CD 스크립트 수정
+ CD 스크립트에서 잘못적은 내용을 다시 작성하겠습니다.
=> 🔀 :: CD 스크립트 수정

.github/workflows/CD.yml
+ cd 에서 에러가 발생했습니다.
+ 환경변수명을 수정하였습니다.
=> 🔀 :: cd 스크립트 오류

goms-application/src/main/kotlin/com/goms/v2/domain/account/data/dto/ProfileDto.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/dto/response/ProfileHttpResponse.kt
코드를 보는 중에 import문이 쓰이지 않지만 그대로 있어 삭제하였습니다.
불필요한 import문 삭제하였습니다.
=> 🔀 :: 불필요한 import문 삭제

goms-application/src/main/kotlin/com/goms/v2/domain/account/data/dto/ProfileDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/QueryAccountProfileUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/late/data/dto/LateRankDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/late/usecase/QueryLateRankUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/outing/data/dto/OutingAccountDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/QueryOutingAccountUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/SearchOutingAccountUseCase.kt, goms-application/src/test/kotlin/com/goms/v2/common/AnyValueObjectGenerator.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/dto/response/ProfileHttpResponse.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/mapper/AccountDataMapper.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/late/dto/LateRankHttpResponse.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/late/mapper/LateDataMapper.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/dto/response/OutingAccountHttpResponse.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/mapper/OutingDataMapper.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/late/LateControllerTest.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt
+ Response Dto에 필드를 추가하였습니다.
+ 학생 정보를 반환하는 Dto에 학생의 과를 명시하는 `Major` 필드를 추가하였습니다.
+ `Major` : [ SW_DEVELOP, SMART_IOT, AI ] 이렇게 3개의 enum값으로 이루어져 있습니다.
=> 🔀 :: response dto 필드 추가

goms-application/src/test/kotlin/com/goms/v2/domain/auth/SignUpUseCaseTest.kt
+ 회원가입 usecase 테스트 코드
+ SignUpUseCase에 대한 테스트코드를 작성하였습니다.
=> 🔀 :: 회원가입 UseCase 테스트 코드

goms-application/src/test/kotlin/com/goms/v2/common/AnyValueObjectGenerator.kt, goms-application/src/test/kotlin/com/goms/v2/domain/auth/SignInUseCase.kt
+ 로그인 UseCase 테스트코드 작성
+ SignInUseCase에 대한 테스트코드를 작성하였습니다.
=> 🔀 :: 로그인 UseCase 테스트 코드

goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/dto/SendAuthCodeDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/event/CreateAuthenticationEvent.kt, goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/event/CreateAuthenticationEventHandler.kt, goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/SendAuthCodeUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/VerifyAuthCodeUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/domain/auth/AuthCode.kt, goms-domain/src/main/kotlin/com/goms/v2/domain/auth/Authentication.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/mapper/AuthCodeMapper.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/entity/AuthCodeRedisEntity.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/entity/AuthenticationRedisEntity.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/mapper/AuthenticationMapper.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/repository/AuthCodeRedisRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/repository/AuthCodeRepositoryImpl.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/repository/AuthenticationRedisRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/repository/AuthenticationRepositoryImpl.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/email/EmailSendAdapter.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/AuthController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/dto/request/SendAuthCodeHttpRequest.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/mapper/AuthCodeDataMapper.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/auth/AuthControllerTest.kt
- 이메일 인증 API를 구현했습니다.
- 인증번호 전송 API를 추가했습니다.
- 인증번호 검증 API를 추가했습니다.
=> 🔀 :: 이메일 인증 API

goms-application/src/test/kotlin/com/goms/v2/domain/account/UpdatePasswordUseCaseTest.kt
+ 비밀번호 변경 usecase 테스트 코드
+ 비밀번호 변경 usecase에 대한 테스트코드를 작성하였습니다.
=> 🔀 :: 비밀번호 변경 usecase 테스트 코드

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/DeleteOutingUseCase.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
- 외출자 삭제 API를 추가했습니다.
- 외출자 삭제 UseCase를 추가했습니다.
- 외출자 삭제 url을 추가했습니다.
- 외출자 삭제 테스트 코드를 추가했습니다.
=> 🔀 :: 외출자 삭제 API

goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/LogoutUseCase.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/AuthController.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/auth/AuthControllerTest.kt
* 로그아웃을 할 수 있는 api를 만들었습니다.
* 로그아웃하는 UseCase를 만들었습니다.
* SecurityConfig에 url을 추가하였습니다.
=> 🔀::로그아웃 api 추가

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/GetLateAccountUseCase.kt, goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/GetLateAccountUseCaseTest.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/late/LateRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/repository/LateJpaRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/repository/LateRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt
+ 테스트코드 작성
+ 지각자를 반환하는 usecase에 대한 테스트코드를 작성하였습니다.
+ List로 반환하는 함수는 null을 반환하지 않고 그냥 빈 함수를 반환해서 null에 대한 예외처리르 삭제했습니다.
=> 🔀 :: 지각자 리스트 테스트 코드

goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/LogoutUseCase.kt, goms-application/src/test/kotlin/com/goms/v2/domain/auth/LogOutUseCaseTest.kt
+ 테스트코드 작성
+ 로그아웃 usecase에 대한 테스트코드 작성
=> 🔀 :: 로그아웃 usecase 테스트코드

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/data/dto/AccountDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/QueryAllAccountUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/SearchAccountUseCase.kt, goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/QueryAllAccountUseCaseTest.kt, goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/SearchAccountUseCaseTest.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/dto/response/AllAccountHttpResponse.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/mapper/StudentCouncilDataMapper.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
+ dto 필드 수정
+ 학생 정보를 반환하는 dto에 `Major(전공)` 필드를 추가하였습니다.
=> 🔀 :: dto major 필드 추가

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/data/dto/SearchAccountDto.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/mapper/StudentCouncilDataMapper.kt
+ 학생 검색에서 쿼리문에서 에러가 발생했습니다.
+ 학생 검색에서 gender 키워드를 nullable하게 했습니다.
+ gender에 대한 조건을 쿼리문에 추가하였습니다.
=> 🔀 :: 학생 검색 쿼리문 수정

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/data/dto/SearchAccountDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/SearchAccountUseCase.kt, goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/SearchAccountUseCaseTest.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/account/AccountRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/mapper/StudentCouncilDataMapper.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
+ 학생 검색할때 키워드를 추가하였습니다.
+ major 키워드로 검색할 수 있도록 major 키워드를 추가하였습니다.
=> 🔀 :: 학생 검색 키워드 추가

buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/DependenciesVersions.kt, goms-application/build.gradle.kts, goms-application/src/main/kotlin/com/goms/v2/common/exception/ErrorCode.kt, goms-application/src/main/kotlin/com/goms/v2/domain/account/exception/FileExtensionInvalidException.kt, goms-application/src/main/kotlin/com/goms/v2/domain/account/spi/S3UtillPort.kt, goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/UploadImageUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/domain/account/Account.kt, goms-infrastructure/build.gradle.kts, goms-infrastructure/src/main/kotlin/com/goms/v2/GomsV2Application.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/aws/s3/AwsS3Config.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/aws/s3/S3Util.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/aws/s3/S3UtilAdapter.kt, goms-infrastructure/src/main/resources/application.yml, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt
* 프로필 이미지를 수정할 수 있는 api를 만들었습니다.
* aws yml 추가
* S3Util 추가
* AwsS3Config 추가
* uploadImageUseCase 추가
=> 🔀 :: 프로필 이미지 수정

goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt
+ controller 테스트코드 작성
+ 프로필 이미지 업로드 controller에 대한 테스트코드를 작성하였습니다.
=> 🔀 :: 프로필 이미지 업로드 controller 테스트 코드

goms-application/src/test/kotlin/com/goms/v2/domain/account/UploadImageUseCaseTest.kt
+ controller 테스트코드를 작성하였습니다.
+ 프로필 이미지 업로드 usecase에 대한 테스트코드를 작성하였습니다.
=> 🔀 :: 프로필 이미지 업로드 usecase 테스트 코드

goms-application/src/test/kotlin/com/goms/v2/domain/notification/SetDeviceTokenUseCaseTest.kt
+ usecase 테스트코드 작성
+ fcm 토큰을 저장하는 usecase에 대한 테스트코드를 작성하였습니다.
=> 🔀 :: fcm 토큰 저장 usecase 테스트코드

goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt
+ api 권한 변경
+ fcm 토큰을 저장하는 api에 대한 access 권한을 변경하였습니다.
=> 🔀 :: api access 권한 변경

goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/DeleteOutingUseCaseTest.kt
=> 🔀 :: 외출자 삭제 테스트 코드

goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/dto/request/SignUpHttpRequest.kt
+ 비밀번호 정규식 변경
+ 기존에 숫자를 포함하던 정규식에서 숫자를 제거하였습니다.
=> 🔀 :: 비밀번호 정규식 변경

goms-application/src/main/kotlin/com/goms/v2/common/exception/ErrorCode.kt, goms-application/src/main/kotlin/com/goms/v2/domain/account/exception/ProfileUrlNotExistException.kt, goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/DeleteImageUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/domain/account/Account.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt
프로필에 등록되어있는 이미지를 삭제하는 api를 만들었습니다.
* DeleteImageUseCase 추가
=> 🔀 :: 프로필 이미지 삭제 api

goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/RequestLogFilter.kt
+ try-catch 문을 추가하겠습니다.
+ request log filter에 try catch문을 추가하였습니다.
=> 🔀 :: try-catch 문 추가

goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/RequestLogFilter.kt
+ try-catch 문 삭제
+ 테스트를 위해 작성해놓은 try-catch 문을 삭제하였습니다.
=> 🔀 :: try-catch 문 삭제

goms-application/src/main/kotlin/com/goms/v2/domain/notification/usecase/DeleteDeviceTokenUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/notification/DeviceTokenRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/notification/repository/DeviceTokenRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/notification/NotificationController.kt
+ device token을 삭제시켜 알림이 못하게 하겠습니다.
+ device token을 삭제하는 API를 구현하였습니다.
=> #214 device token 삭제하기

goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/AuthController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/OutingController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt
- Controller에서 결과값이 없는 메서드들의 스코프 함수를 변경하였습니다.
- let에서 run으로 변경하였습니다.
=> 🔀 :: Controller 스코프 함수 변경

goms-application/src/main/kotlin/com/goms/v2/domain/account/data/dto/ChangePasswordDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/account/exception/PasswordNotMatchException.kt, goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/ChangePasswordUseCase.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/dto/request/ChangePasswordRequest.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/mapper/AccountDataMapper.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt
로그인 상태에서 이메일 인증없이 비밀번호를 변경할 수 있는 api를 개발하였습니다
* AccountController에서 changePassword 추가
* toDomain 추가
* ChangePasswordDto 추가
* ChangePasswordRequest 추가
* ChangePasswordUseCase 추가
=> 🔀 :: 로그인 상태에서 비밀번호 변경

goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/ChangePasswordUseCase.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt
+ 비밀번호 재설정 예외처리 에러 발생
+ 현재 유저의 비밀번호와 일치하는 검사에서 if문에 `!`를 추가하였습니다.
=> #223 update password exception

goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/OutingController.kt
+ request param을 추가하였습니다.
+ 외출현황 리스트에 name 파라미터를 required=false로 추가하였습니다.
=> #228 request param

buildSrc/src/main/kotlin/Dependencies.kt, docker-compose-monitoring.yml, goms-infrastructure/build.gradle.kts, goms-infrastructure/src/main/resources/application.yml, goms-infrastructure/src/main/resources/prometheus.yml
- 모니터링 시스템을 구축했습니다.
- actuator, prometheus, grafana를 이용해서 모니터링 시스템을 구축했습니다.
=> 🔀 :: 모니터링 시스템 구축

goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/dto/WithdrawDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/WithdrawUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/account/AccountRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/mapper/AccountDataMapper.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/dto/request/WithdrawHttpRequest.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt
=> 🔀 :: 회원탈퇴 기능

goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/WithdrawUseCase.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt
+ DeleteMapping 메서드에서 RequestBody로 요청 불가능
+ RequestBody에서 PathVariable로 변경
=> 🔀 :: 회원탈퇴 요청방식 변경

goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt
+ security config api 수정
+ 회원탈퇴 api 를 수정하였습니다.
=> 🔀 :: security config api url

goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/email/EmailSendAdapter.kt
+ 이메일 전송을 비동기로 구현하였습니다.
+ async 어노테이션을 추가하였습니다.
=> 🔀 :: send email async

goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/OutingUseCase.kt
=> 🔀 :: qr exception

goms-infrastructure/src/main/resources/application.yml
=> add :: multi part size

goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/OutingUseCase.kt
+ 외출 예외처리 추가
+ 외출할때 요청받는 UUID가 유효한 UUID인지 검증하는 로직을 추가하였습니다.
=> 🔀 :: outing uuid exception

goms-infrastructure/src/main/resources/junit-platform.properties
+ junit 테스트 병렬 수행
+ junit-platform.properties 파일을 추가하였습니다.
=> 🔀 :: junit-platform.properties

buildSrc/src/main/kotlin/Dependencies.kt, goms-application/src/main/kotlin/com/goms/v2/domain/late/data/dto/LateRankDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/late/usecase/QueryLateRankUseCase.kt, goms-infrastructure/build.gradle.kts, goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/RedisCacheConfig.kt
+ 지각자 랭킹 조회 캐시 적용
+ 지각자 정보를 조회하면 redis에 저장되어 캐시로 저장되도록 구현하였습니다.
https://github.com/team-haribo/GOMS-Backend-V2/issues/259
=> #259 late rank cache

Dockerfile
=> 🔀 :: docker file

goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/DeleteImageUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/OutingUseCase.kt
+ 프로필 정보 수정시 캐시 데이터 삭제
+ 프로필 이미지를 삭제하면 캐시 데이터 삭제
+ 외출하면 프로필에 있는 외출상태 캐시 데이터 삭제
=> #272 profile cache outing status

docker-compose.yml
+ docker compose yml파일 추가
+ mysql, redis에 대한 정보를 추가하였습니다.
=> 🔀 :: docker compose yml

docker-compose.yml
=> add :: docker compose spring service

docker-compose.yml
+ aws cloud watch를 사용해서 log를 관리
+ docker-compose.yml 파일 spring service에 aws log 설정
=> #300 cloud watch 설정

docker-compose.yml
=> add :: mysql, redis volume

.github/workflows/CI-CD.yml, goms-application/src/main/kotlin/com/goms/v2/domain/outing/scheduler/OutingScheduler.kt
+ 월, 수 외출제로 변경에  따른 scheduler 수정
+ 기존의 수요일 7시26분에만 저장하던 지각자를 월요일에도 저장하도록 수정
+ 월, 수 외출제 변경에 따라 수정되야 하는 다른 부분이 있는지 확인해주세요.
=> #307 outing scheduler date

goms-infrastructure/src/main/kotlin/com/goms/v2/GomsV2Application.kt
=> add :: enable redis repositories

goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/aws/s3/AwsS3Config.kt
- AWSS3Config에 open 키워드를 추가했습니다.
- may not be final 오류를 해결하기 위해 open 키워드를 추가했습니다.
=> 🔀 :: open 키워드 추가

buildSrc/src/main/kotlin/AllOpen.kt, goms-infrastructure/build.gradle.kts, goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/aws/s3/AwsS3Config.kt
- allOpen 플러그인을 수정했습니다.
- allOpen 플러그인에 Configuration을 추가했습니다.
=> 🔀 :: allOpen 플러그인 수정

buildSrc/src/main/kotlin/PluginVersions.kt
- 플러그인 버전을 kotlin 버전에 맞게 수정했습니다.
=> 🔀 :: 플러그인 버전 수정

goms-application/src/main/kotlin/com/goms/v2/domain/notification/scheduler/NotificationScheduler.kt, goms-application/src/main/kotlin/com/goms/v2/domain/notification/usecase/SendNotificationUseCase.kt, goms-domain/src/main/kotlin/com/goms/v2/domain/notification/NotificationType.kt, goms-domain/src/main/kotlin/com/goms/v2/domain/notification/Topic.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/notification/FcmAdapter.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/notification/config/FcmConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/notification/property/FcmProperties.kt, goms-infrastructure/src/main/resources/application.yml, goms-presentation/src/main/kotlin/com/goms/v2/domain/notification/NotificationController.kt
=> 🔁 FCM 외출제 전 알림 추가

goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/notification/NotificationController.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt
=> 🔁 푸시 알림 테스트 API 구현

buildSrc/src/main/kotlin/DependenciesVersions.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/notification/FcmAdapter.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/notification/config/FcmConfig.kt
FCM 대상을 multicast에서 all로 수정했습니다.
=> 🔁 FCM 대상 수정

goms-application/src/main/kotlin/com/goms/v2/domain/notification/usecase/SendNotificationUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/outingDate/usecase/SetTodayOutingUseCase.kt
=> 🔁 FCM 스케쥴 조건문 변경

goms-application/src/main/kotlin/com/goms/v2/domain/notification/data/dto/SendCustomNotificationDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/notification/usecase/SendCustomNotificationUseCase.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/notification/NotificationController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/notification/dto/request/SendCustomNotificationRequest.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/notification/mapper/NotificationDataMapper.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outingDate/OutingDateController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/outingDate/dto/request/SetTodayOutingRequest.kt
=> 🔁 디스코드 푸시 알림 전송 기능 추가

goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/notification/FcmAdapter.kt
=> 🔁 AOS와 iOS 푸시 알림 소리 추가

goms-application/src/main/kotlin/com/goms/v2/common/exception/ErrorCode.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/data/dto/AccountDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/data/dto/SearchAccountDto.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/exception/OutingAlreadyExistException.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/ForcingOutingUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/QueryAllAccountUseCase.kt, goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/SearchAccountUseCase.kt, goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/QueryAllAccountUseCaseTest.kt, goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/SearchAccountUseCaseTest.kt, goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingJpaRepository.kt, goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingRepositoryImpl.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/dto/response/AllAccountHttpResponse.kt, goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/mapper/StudentCouncilDataMapper.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
> 학생회 권한의 사용자가 강제로 다른 사용자를 외출시키는 API를 구현하였습니다
=> 🔁 사용자 강제 외출 기능

goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingBlackListRepositoryImpl.kt
> ``Null``이 요소로 들어간 List에서 Null을 필터링 하도록 코드를 조정하여 map 실행 시 NPE를 방지하였습니다
=> 🔁 블랙리스트 조회 시 Redis에 Value가 없을 때 NPE 발생 수정

goms-infrastructure/src/main/kotlin/com/goms/v2/global/advice/GradeExclusionAdvice.kt
일부 누락 되었던 코드를 복구하고 주석을 강화하며 성능을 개선하였습니다
[x] 기존 코드 리팩터링
=> 6기 정보 필터링 클래스 개선

goms-infrastructure/src/main/kotlin/com/goms/v2/global/advice/GradeExclusionAdvice.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/late/LateControllerTest.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt, goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
> 6기 학생 정보를 필터링 하는 클래스를 개선하고 주석을 최종적으로 보강하였습니다
[x] JavaDoc 주석 보강
[x] 필터링 기능 성능 향상
=> 🔄️ 6기 학생 필터링 기능 구성

goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/SignUpUseCase.kt
매년 변경을 요하던 기수 추출 메서드를 서버시각을 기준으로 기수를 추출하도록 유연하게 변경하였습니다
=> 🔄️ 기수 추출 메서드 하드코딩 개선
