goms-domain/src/main/kotlin/com/goms/v2/domain/auth/RefreshToken.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/global/event/SaveRefreshTokenEventHandler.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/entity/RefreshTokenJpaEntity.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/mapper/RefreshTokenMapper.kt

+ RefreshTokenMapper에 대한 RefreshTokenMapperImpl 클래스에서 에러가 발생해서 삭제를 했는데 다시 생기지 않는 이슈가 발생했습니다.
+ RefreshTokenMapperImpl 클래스를 다시 생성되는 과정에서 RefreshToken과 RefreshTokenJpaEntity의 expiredAt 타입이 달라서 RefreshTokenMapperImpl가 생기지 않습니다.
+ RefreshTokenJpaEntity와 RefreshToken의 expiredAt의 타입을 Int로 통일하였습니다.

🔀 :: Mapper에 toDomain Mapper 추가

---

goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/dto/GAuthUserInfoDto.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/GAuthAdapter.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/mapper/GAuthDataMapper.kt

- GAuth 로그인이 `프로필URL`이 null인 사람은 로그인인 안되는 에러가 발생했습니다.
- GAuth에 정보를 받아오는 dto에서 `프로필URL` 에 `?`를 붙여서 null인 정보도 dto에 저장할 수 있도록 수정하였습니다.
- 패키지를 이동시켰습니다.

🔀 :: GAuth 로그인 에러 고치기

---

goms-infrastructure/src/main/kotlin/com/goms/v2/global/exception/handler/GlobalExceptionHandler.kt

+ MethodArgumentNotValidException 핸들러가 되지않아 수정 하였습니다.
+ MethodArgumentNotValidException 핸들러의 ErrorResponse message 값을 수정하였습니다.
+ HttpMessageNotReadableException 핸들러를 추가하였습니다.

MethodArgumentNotValidException 핸들러 수정

---

goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/SignInUseCase.kt
goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/GrantAuthorityUseCaseTest.kt
goms-domain/src/main/kotlin/com/goms/v2/repository/account/AccountRepository.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt

- save() 메서드에 대한 반환타입을 만들었습니다.
- 예전에는 `save()`메서드에 대한 반환타입이 없었습니다.
- 로그인 테스트코드를 작성하는 과정에서 `save()`메서드의 반환값이 필요해서 `Account` 객체의 반환값을 추가하였습니다.
- `save()`에서 `Account`를 반환하게 수정을 하면 기존의 `GrantAuthorityUseCaseTest` 테스트코드에서 `Unit`으로 반환해야하는 걸 `Account`객체의 타입으로 반환하도록 수정해야하는데 제가 `GrantAuthorityUseCaseTest`에서 `Account`객체로 변경하지 않아서 ci 검사도중 테스토코드 에러가 발생하였습니다.
- `save()` 메서드에 대한 반환타입을 `Account`로 지정하였습니다.
- 테스트코드에서 `save()` 메서드를 사용할때 `Account`객체를 반환하게 수정하였습니다.
- 잘못된 컨벤션이 있는지 확인해주세요.
- 또 다른 컨플릭트가 날 만한 로직이 있는지 확인해주세요.

🔀 :: 메서드 반환 타입에 변경에 따른 테스트코드 수정

---

goms-application/src/main/kotlin/com/goms/v2/domain/auth/spi/TokenParsePort.kt
goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/ReissueTokenUseCase.kt
goms-application/src/test/kotlin/com/goms/v2/domain/auth/ReissueTokenUseCaseTest.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/TokenParserAdapter.kt

- 클래스명을 변경하였습니다.
- 기존의 TokenParserPort를 TokenParsePort로 변경하였습니다.
- 클래스명이 바뀌지 않은 곳이 있는지 확인해주세요.

🔀 :: TokenParsePort로 클래스명 변경

---

goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/SendEmailUseCase.kt

- 이메일 로그인은 GOMS 회원인 사용자만 가능하기 때문에 이메일 전송 전에 회원검증을 해야합니다.
- 이메일 로그인을 위한 이메일 전송 전에 회원검증 로직을 추가하였습니다.

🔀 :: 이메일 전송하기 전에 GOMS 회원인지 검증하기

---

goms-application/src/main/kotlin/com/goms/v2/domain/outing/scheduler/OutingScheduler.kt

- 7시25분까지 외출시간이어서 25분에 지각자가 저장이 되면 안됩니다.
- 7시26분에 지각자가 저장이 되야 합니다.
- 지각자를 저장하는 시간을 7시25분에서 7시26분으로 변경하였습니다.

🔀 :: 지각자 저장 시간 변경

---

goms-application/src/main/kotlin/com/goms/v2/common/exception/ErrorCode.kt
goms-application/src/main/kotlin/com/goms/v2/common/util/AuthenticationValidator.kt
goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/event/DeleteAuthenticationEvent.kt
goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/event/DeleteAuthenticationEventHandler.kt
goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/SignUpUseCase.kt
goms-application/src/test/kotlin/com/goms/v2/domain/auth/SignUpUseCaseTest.kt
goms-domain/src/main/kotlin/com/goms/v2/repository/auth/AuthenticationRepository.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/repository/AuthenticationRepositoryImpl.kt

+ 회원가입 시 이메일 인증을 한 사용자 인지 구분하는 검증 로직을 추가하였습니다.
+ 회원가입을 할때 이메일 인증에 성공해서 Authentication 객체가 생성되었는지 확인하는 로직을 추가하였습니다.
+ 인증된 사용자인지 확인이 되고 회원가입이 마무리 되면 Authentication 객체를 삭제하는 Spring Event를 추가하였습니다.
+ 인증되지 않은 사용자일때 발생되는 예외처리의 상태코드를 변경하였습니다.
+ 404 -> 401

🔀 :: 회원가입 이메일 인증 로직 추가

---

goms-application/src/main/kotlin/com/goms/v2/common/exception/ErrorCode.kt
goms-application/src/main/kotlin/com/goms/v2/domain/account/data/dto/PasswordDto.kt
goms-application/src/main/kotlin/com/goms/v2/domain/account/exception/DuplicatedNewPasswordException.kt
goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/UpdatePasswordUseCase.kt
goms-domain/src/main/kotlin/com/goms/v2/domain/account/Account.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/entity/AccountJpaEntity.kt
goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt
goms-presentation/src/main/kotlin/com/goms/v2/domain/account/dto/request/UpdatePasswordRequest.kt
goms-presentation/src/main/kotlin/com/goms/v2/domain/account/mapper/AccountDataMapper.kt
goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt

+ 비밀번호 재설정 API 
+ entity에서 password를 지정할때 val에서 var로 변경하였습니다.
+ `UpdatePasswordRequest` dto를 `PasswordDto`로 타입을 변경하는 Mapper를 구현하였습니다.
+ 비밀번호 변경 UseCase를 구현하였습니다.
+ `AccountController`에 대한 api 테스트코드를 작성하였습니다.

🔀 :: 비밀번호 재설정 API

---

goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingJpaRepository.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingRepositoryImpl.kt

+ 기존 `findAllByOrderByCreatedTimeDesc` 쿼리메서드에서 n + 1 문제가 발생하였습니다.
+ queryDSL을 통해 fetch join을 하여 n + 1 을 해결했습니다.

🔀 :: n + 1 문제 해결

---

goms-application/src/main/kotlin/com/goms/v2/domain/account/spi/S3UtillPort.kt
goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/UpdateImageUseCase.kt
goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/UploadImageUseCase.kt
goms-application/src/test/kotlin/com/goms/v2/domain/account/UploadImageUseCaseTest.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/aws/s3/S3UtilAdapter.kt
goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt
goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt

프로필 이미지를 있던 상태에서 변경할 수 있는 api를 만들었습니다.
* updateImageUseCase 추가
* s3UtilPort에 validImage, deleteImage 추가
* s3UtilAdapter에 validImage, deleteImage 로직 추가
* updateImageUseCase와 uploadImageUseCase에 중복되는 코드를 s3Util에 메서드 추가하여 코드 정리

🔀 :: 프로필 이미지 변경 api

---

goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt

+ 비밀번호 재설정 api 접근 궈한 변경
+ 로그인 과정에서 비밀번호를 재설정 할 수 있으므로 토큰 없이도 api를 호출할 수 있어야합니다.
+ api에 대한 접근 권한을 hasAnyAuthority에서 permitAll로 변경하였습니다.

 :: 비밀번호 재설정 api 권한 변경

---

goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/DeleteImageUseCase.kt

DeleteImage에서 profile_url이 삭제되지않는 것을 수정하였습니다
* DeleteImageUseCase에 .save() 추가

🔀 :: DeleteImage 로직 수정

---

goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/WithdrawUseCase.kt
goms-domain/src/main/kotlin/com/goms/v2/repository/late/LateRepository.kt
goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingRepository.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/repository/LateJpaRepository.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/repository/LateRepositoryImpl.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingJpaRepository.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingRepositoryImpl.kt

+ 회원탈퇴 할때 유저의 지각정보, 외출정보 삭제
+ 회원탈퇴 로직에서 유저의 지각정보와 외출정보를 함께 삭제하도록 하였습니다.

#250 with draw delete info

---

goms-domain/src/main/kotlin/com/goms/v2/domain/auth/Authentication.kt

+ 이메일 인증 권한 시간 수정
+ 이메일 인증을 하면서 필요한 authentication에 유효기간을 1시간에서 5분으로 수정하였습니다.
+ 이 작업을 통해 이메일 전송 횟수가 5번이 넘었을때 대기시간을 5분으로 설정할 수 있습니다.

🔀 :: authentication expiredAt value

---

buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependenciesVersions.kt
goms-application/src/main/kotlin/com/goms/v2/domain/account/data/dto/ProfileDto.kt
goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/QueryAccountProfileUseCase.kt
goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/UpdateImageUseCase.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingRepositoryImpl.kt
goms-presentation/build.gradle.kts
goms-presentation/src/main/kotlin/com/goms/v2/domain/account/mapper/AccountDataMapper.kt
goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt

+ 프로필 조회 API에 캐싱기능을 추가하였습니다.
+ 프로필을 조회하면 캐시에 조회된 데이터를 저장하도록 하였습니다.
+ 프로필 이미지를 수정하면 캐시에 데이터가 삭제되도록 하였습니다. (프로필 이미지 수정후 프로필을 다시 조회하면 그때 다시 수정된 프로필이 캐시에 저장되도록 구현)
+ d3216f4b1d244730aec3868d0ae82d99bdd0ffb7 
현재 이와같이 기존의 `isOuting`, `isBlackList`를 `outing`, `blackList`로 바꾼 이유는 redis에서 값을 저장할때 `is` keyword 저장을 지원해주지 않기 때문에 캐시를 저장할때 자동으로 is를 생략하고 outing만 저장합니다.
그래서 저장된 캐시를 불러올때 에러가 발생해서 일단은 `outing`으로 변수명을 변경하였습니다. 추후에 `is` keyword로 변수명을 수정하고 다른 방법으로 리펙토링 하겠습니다. 참고해주세요 !

#262 profile cache

---

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/DeleteOutingUseCase.kt
goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/DeleteOutingUseCaseTest.kt

+ 학생회가 외출자를 외출자 명단에서 삭제시키면 외출상태가 `외출중` 에서 `외출 대기중` 으로 상태가 변경되어야 합니다.
+ 외출자 명단에서 삭제할때 학생 정보에 대한 캐시를 삭제하지 않으면 복귀를 해도 `외출중`이라는 상태를 캐시에서 불러옵니다.
+ 사용자 프로필에 대한 캐시 데이터가 업데이트 될 수 있도록 외출 상태가 변경되면 프로필 캐시를 삭제하도록 하였습니다.

# 280 feat/outing profile cache delete

---

goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/GrantAuthorityUseCase.kt

+ 학생회가 사용자의 권한을 변경하면 학생의 권한이 변경되어야 합니다.
+ 프로필에서 권한이 변경될때 학생 정보에 대한 캐시를 삭제하지 않으면 권한이 바뀌어도 이전 권한 페이지가 보입니다.
+ 사용자 프로필에 대한 캐시 데이터가 업데이트 될 수 있도록 학생의 권한이 변경되면 프로필 캐시를 삭제하도록 하였습니다.

#283 feat/user profile cache delete

---

goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/DeleteImageUseCase.kt
goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/QueryAccountProfileUseCase.kt
goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/UpdateImageUseCase.kt
goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/OutingUseCase.kt
goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/DeleteOutingUseCase.kt
goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/GrantAuthorityUseCase.kt
goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/DeleteOutingUseCaseTest.kt

+ 학생 프로필을 저장하는 캐시를 삭제하였습니다.
+ 프로필을 조회하면 캐시에 저장해놓고 캐시에서 데이터를 가져오도록 구현했는데, 학생 프로필 특성상 변경사항이 많아서(외출/복귀, 프로필 사진 변경, 권한 변경 등) 캐시에 저장 안하기로 결정하였습니다.

🔀 :: 개인 프로필 정보를 캐시에 저장하는 기능을 제거하였습ㄴ디ㅏ.

---

goms-application/src/main/kotlin/com/goms/v2/domain/auth/spi/EmailSendPort.kt
goms-application/src/main/kotlin/com/goms/v2/domain/auth/spi/NotificationSendPort.kt
goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/SendAuthCodeUseCase.kt
goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/email/MailSendAdapter.kt

+ 알림 전송 코드에 OCP를 적용시켰습니다.
+ `NotificationSendPort`이라는 추상화된 인터페이스를 만들었습니다.
+ `NotificationSendPort` 인터페이스를 구현하는 이메일 전송 클래스를 만들었습니다.
+ 추후에 알림 전송 기능으로 문자 전송 기능이 추가될때 기존의 코드를 변경하는 것이 아닌`NotificationSendPort` 인터페이스를 구현하는 또 다른 클래스 문자 전송 클래스를 만들어서 문자 전송 기능을 구현할 수 있도록 설계하였습니다.

🔀 :: notification port, mail send adapter ocp 적용

---

goms-infrastructure/src/main/kotlin/com/goms/v2/global/advice/GradeExclusionAdvice.kt

> 6기 데이터가 클라이언트로 반환되는 것을 막지만 DB에서 데이터를 삭제하는 것은 당장 진행하지 않기로 함에 따라 6기 학생 데이터를 응답 객체에서 필터링하도록 구현하였습니다
추후 6기 학생 데이터 삭제 시 해당 클래스를 제거하는게 좋을 것 같습니다

🔁 6기 학생 데이터 필터링 클래스 구현
